feature_extraction:
  # Topics:
  heightMapTopic: "/height_mapping/map/gridmap" # Feature extraction subscribes to this topic
  featureMapTopic: &feature_map_topic "/traversability_learning/feature_grid"
  featureMapCloudTopic: &feature_cloud_topic "/traversability_learning/feature_cloud" # Label generator subscribes to this topic
  surfaceNormalTopic: &surface_normal_topic "/traversability_learning/surface_normals"

traversability_prediction:
  # Topics:
  traversabilityMapTopic: &traversability_map_topic "/traversability_learning/traversability_grid"
  traversabilityMapCloudTopic: &traversability_cloud_topic "/traversability_learning/traversability_cloud"

  # Parameters:
  traversabilityThreshold: 0.5
  traversabilityPredictionRate: 10 # Hz

label_generation:
  # Topics:
  labelMapTopic: "/traversability_learning/label_cloud"

  # Labeling Parameters:
  footprintRadius: 0.5 # meters -> positive label generation
  maxAcceptableTerrainStep: 0.1 # meters -> negative label generation
  maxAcceptableTerrainSlope: 20 # degrees -> negative label generation

  ## Duration
  footprintRecordingRate: 10 # Hz
  visualizationRate: 10 # Hz

feature_map_visualization:
  grid_map_topic: *feature_map_topic
  grid_map_visualizations:
    # Point cloud
    - name: *feature_cloud_topic
      type: point_cloud
      params:
        layer: elevation
    # Surface normals
    - name: *surface_normal_topic
      type: vectors
      params:
        layer_prefix: normal_
        position_layer: elevation
        scale: 0.3
        line_width: 0.01
        color: 15600153 # red

traversability_map_visualization:
  grid_map_topic: *traversability_map_topic
  grid_map_visualizations:
    # Point cloud
    - name: *traversability_cloud_topic
      type: point_cloud
      params:
        layer: elevation