grid_map_topic: "/traversability_estimation/map/gridmap"
grid_map_visualizations:
  # Point cloud
  - name: "/traversability_estimation/map/pointcloud"
    type: point_cloud
    params:
      layer: elevation