grid_map_topic: "/traversability_estimation/features/gridmap"
grid_map_visualizations:
  # Point cloud
  - name: "/traversability_estimation/features/pointcloud"
    type: point_cloud
    params:
      layer: elevation
  # Surface normals
  - name: "/traversability_estimation/features/surface_normals"
    type: vectors
    params:
      layer_prefix: normal_
      position_layer: elevation
      scale: 0.1
      line_width: 0.005
      color: 15600153 # red
