grid_map_topic: "/lesta/prediction/traversability"
grid_map_visualizations:
  # Point cloud
  - name: "/lesta/prediction/traversability_cloud"
    type: point_cloud
    params:
      layer: elevation
  # Surface normals
  - name: "/lesta/feature/surface_normals"
    type: vectors
    params:
      layer_prefix: feature/normal_
      position_layer: elevation
      scale: 0.2
      line_width: 0.010
      color: 15600153 # red
  # Map region
  - name: "/lesta/prediction/map_region"
    type: map_region
    params:
      color: 10526880  # light blue
      line_width: 0.03
