## -- Coordinate Frame Ids
frameId_map: "map"
frameId_robot: "base_link"

###########################
## Local Terrain Mapping ##
###########################

local_terrain_mapping:
  ## -- Topics
  SubscribedTopic:
    pointcloud: "/velodyne_tilted/velodyne_points"
  PublishingTopic:
    elevation_map: "map"
    descriptor_map: "descriptor"

  ## -- Terrain Map
  ElevationMap:
    grid_resolution: 0.1
    map_length_x: 12.0
    map_length_y: 12.0

  ## -- Local Map Pose (Use TF Tree)
  PoseUpdate:
    duration: 0.05 # 20Hz

############################
## Global Terrain Mapping ##
############################

global_terrain_mapping:
  ## -- Topics
  SubscribedTopic:
    pointcloud: "/velodyne_tilted/velodyne_points"
  PublishingTopic:
    elevation_map: "map"
    descriptor_map: "descriptor"

  ## -- Terrain Map
  ElevationMap:
    grid_resolution: 0.1
    map_length_x: 600.0
    map_length_y: 600.0
    min_height_threshold: -0.7 # filtering pointclouds for map update
    max_height_threshold: 0.7
    min_range_threshold: 0.5 # range in 2D
    max_range_threshold: 10.0

  ## -- Global Map Visualization
  Visualization:
    duration: 2.0 # [sec]

############################
## Traversability Mapping ##
############################

traversability_mapping:
  ## -- Topics
  PublishingTopic:
    traversability_map: "map"

  stepThreshold: 0.3 # meter
  slopeThreshold: 21 # degree

  ## Robot-dependent Variables
  robotRadiusMeter: 0.15

  ## Timer
  globalMapUpdateTimeInterval: 0.1
  featureMapUpdateTimeInterval: 0.1
  loopRate: 10